"""initial_schema

Revision ID: 7167bbf92946
Revises: 
Create Date: 2026-05-07 16:03:53.189424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7167bbf92946'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('round_types', sa.JSON(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'done', 'cancelled')", name='ck_interview_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outbound_idempotency',
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('message_sid', sa.String(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('idempotency_key')
    )
    op.create_table('wa_window_state',
    sa.Column('recipient_e164', sa.String(), nullable=False),
    sa.Column('last_inbound_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_template_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('recipient_e164')
    )
    op.create_table('mock_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('interview_id', sa.Integer(), nullable=False),
    sa.Column('round_type', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transcript_json', sa.String(), nullable=True),
    sa.Column('rubric_json', sa.String(), nullable=True),
    sa.Column('critique_json', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prep_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('interview_id', sa.Integer(), nullable=False),
    sa.Column('plan_md', sa.String(), nullable=False),
    sa.Column('time_budget_min', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('self_rating', sa.String(), nullable=True),
    sa.Column('skipped', sa.Boolean(), nullable=False),
    sa.CheckConstraint("self_rating IN ('easy', 'medium', 'hard') OR self_rating IS NULL", name='ck_prepplan_self_rating'),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weak_patterns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pattern', sa.String(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_session_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['source_session_id'], ['mock_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weak_patterns')
    op.drop_table('prep_plans')
    op.drop_table('mock_sessions')
    op.drop_table('wa_window_state')
    op.drop_table('outbound_idempotency')
    op.drop_table('interviews')
    # ### end Alembic commands ###
